// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMykHFxC7v97nALkkGAVlW6zWjsuh6lzA',
    appId: '1:937590169867:web:451aaa61c90b4468d4820e',
    messagingSenderId: '937590169867',
    projectId: 'tcc01-2e62b',
    authDomain: 'tcc01-2e62b.firebaseapp.com',
    storageBucket: 'tcc01-2e62b.firebasestorage.app',
    measurementId: 'G-YV56089D3Z',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCa2bMGDqR1_F6NHnB-VHWSIujrr4AXaww',
    appId: '1:937590169867:android:29b41ffd2d4adfd2d4820e',
    messagingSenderId: '937590169867',
    projectId: 'tcc01-2e62b',
    storageBucket: 'tcc01-2e62b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDaJ9tNLMxHOPpwB3YzcA9mv0O43T5m0LM',
    appId: '1:937590169867:ios:b0888a95c54520add4820e',
    messagingSenderId: '937590169867',
    projectId: 'tcc01-2e62b',
    storageBucket: 'tcc01-2e62b.firebasestorage.app',
    iosBundleId: 'com.example.tcc01',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDaJ9tNLMxHOPpwB3YzcA9mv0O43T5m0LM',
    appId: '1:937590169867:ios:b0888a95c54520add4820e',
    messagingSenderId: '937590169867',
    projectId: 'tcc01-2e62b',
    storageBucket: 'tcc01-2e62b.firebasestorage.app',
    iosBundleId: 'com.example.tcc01',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCMykHFxC7v97nALkkGAVlW6zWjsuh6lzA',
    appId: '1:937590169867:web:da157298a29c1b76d4820e',
    messagingSenderId: '937590169867',
    projectId: 'tcc01-2e62b',
    authDomain: 'tcc01-2e62b.firebaseapp.com',
    storageBucket: 'tcc01-2e62b.firebasestorage.app',
    measurementId: 'G-RQ0Q0T8D9C',
  );
}
